services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    env_file:
      - .env.dev
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+psycopg2://trading:trading@postgres:5432/trading
      STREAMING_INGEST_URL: ${STREAMING_INGEST_URL:-http://streaming:8000}
      STREAMING_SERVICE_TOKEN: ${STREAMING_SERVICE_TOKEN:-reports-token}
      STREAMING_ROOM_ID: ${STREAMING_ROOM_ID:-public-room}
    depends_on:
      - postgres
      - redis
    ports:
      - "8011:8000"

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    env_file:
      - .env.dev
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+psycopg2://trading:trading@postgres:5432/trading
    depends_on:
      - postgres
    ports:
      - "8012:8000"

  prometheus:
    image: prom/prometheus:v2.53.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - auth-service
      - user-service

  grafana:
    image: grafana/grafana:10.4.5
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./docs/observability/dashboards:/var/lib/grafana/dashboards:ro
      - ./infra/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./infra/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata: {}
