[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 100

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203"]

[tool.mypy]
python_version = "3.12"
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
strict = true
plugins = ["pydantic.mypy"]

[tool.pytest.ini_options]
testpaths = ["services"]
addopts = "-q"
pythonpath = ["services/config-service"]