name: Bug report
description: Signaler un bug
title: "[bug] <titre>"
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: Quoi
      description: Décris le bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Étapes
      description: Étapes pour reproduire
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
