name: Feature request
description: Proposer une fonctionnalité
title: "[feat] <titre>"
labels: ["enhancement"]
body:
  - type: textarea
    id: value
    attributes:
      label: Valeur
      description: Quel problème cela résout ?
    validations:
      required: true
  - type: textarea
    id: spec
    attributes:
      label: Spécification
      description: Acceptance criteria / Definition of Done
