global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: fastapi-services
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:8000"]
        labels:
          service: auth-service
      - targets: ["user-service:8000"]
        labels:
          service: user-service
