title = "Tableau de bord KPI"
description = "Suivi consolidé des indicateurs clés pour le programme trading bot."
owners_note = "Mettez à jour les métriques manuelles lors du comité hebdomadaire."

[[kpis]]
id = "onboarding"
name = "Expérience d'onboarding"
description = "Taux de complétion du parcours d'onboarding sur les 7 derniers jours."
owner = "Head of Product"
target = ">= 85 %"
current = "À renseigner"
data_source = "Product analytics"
update_mode = "Manuel"
review_cadence = "Hebdomadaire"
status = "watch"
notes = "Renseigner depuis l'outil d'analytics (Amplitude/Matomo)."

[[kpis]]
id = "e2e_pass_rate"
name = "Taux de réussite des scénarios E2E"
description = "Part de scénarios critiques exécutés avec succès dans la CI."
owner = "QA Lead"
target = "100 %"
current = "En attente du prochain run"
data_source = "Workflow GitHub Actions e2e.yml"
update_mode = "Automatique"
review_cadence = "Quotidienne"
format = "percentage"
status = "on_track"
notes = "Calculé automatiquement à partir du statut du job e2e."

[[kpis]]
id = "mvp_strategy"
name = "Stratégie MVP"
description = "Avancement des fonctionnalités prioritaires définies pour le MVP."
owner = "Product Strategy"
target = "Roadmap MVP livrée à 100 %"
current = "Phase d'exécution"
data_source = "Docs / productboard"
update_mode = "Manuel"
review_cadence = "Bi-hebdomadaire"
status = "watch"
notes = "Mettre à jour selon le comité produit."

[[kpis]]
id = "coverage"
name = "Couverture de tests"
description = "Couverture de code agrégée sur la suite de tests Python."
owner = "Engineering Manager"
target = ">= 80 %"
current = "En attente du prochain run"
data_source = "Rapport coverage.xml"
update_mode = "Automatique"
review_cadence = "Quotidienne"
format = "percentage"
status = "on_track"
notes = "Généré par python -m coverage via make test."

[[kpis]]
id = "community"
name = "Dynamique communauté"
description = "Évolution de la communauté open source (engagement Discord + contributions GitHub)."
owner = "Community Lead"
target = "+10 % de membres actifs / mois"
current = "Collecte à planifier"
data_source = "Discord / GitHub Insights"
update_mode = "Manuel"
review_cadence = "Mensuelle"
status = "at_risk"
notes = "Synchroniser avec l'équipe community pour alimenter la donnée."
