name: ci

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run -a
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements/services.txt
          pip install -r requirements/services-dev.txt

      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium firefox
      - name: Run tests
        run: pytest -q
      - name: Build config-service Docker image
        run: docker build -t config-service:ci ./services/config-service
