name: e2e
on:
  push:
    branches: [ "main", "feat/**" ]
  pull_request:
    branches: [ "main" ]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Up infra
        run: |
          docker compose up -d postgres redis
          docker compose up -d --build auth-service
      - name: Wait for auth-service
        run: |
          for i in {1..30}; do
            curl -sf http://127.0.0.1:8011/health && exit 0
            sleep 2
          done
          echo "auth-service not ready" && exit 1
      - name: Run E2E (bash)
        run: bash ./scripts/e2e/auth_e2e.sh
