name: codex-test

on:
  workflow_call:
    inputs:
      python-version:
        description: Version de Python utilisée pour les tests
        required: false
        default: '3.12'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements/services.txt
          pip install -r requirements/services-dev.txt
      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium
      - name: Run test suite
        run: make test
      - name: Run web dashboard E2E tests
        run: make web-dashboard-e2e
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov
          if-no-files-found: ignore
